/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-05-21 07:35:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class adminDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <title>Admin Dashboard | Dawn Airlines</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome (icons) -->\r\n");
      out.write("  <link rel=\"stylesheet\"\r\n");
      out.write("        href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Chart.js -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    /* ===== PASSENGER-STYLE SIDEBAR CSS (applied to admin JSP) ===== */\r\n");
      out.write("\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      background-color: #f4f6f8;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Sidebar */\r\n");
      out.write("    .sidebar {\r\n");
      out.write("      width: 220px;\r\n");
      out.write("      background: linear-gradient(180deg, #0a1c2c, #123456);\r\n");
      out.write("      color: white;\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar h2 {\r\n");
      out.write("      color: #f6c90e;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("      font-size: 1.3rem;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul {\r\n");
      out.write("      list-style: none;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li {\r\n");
      out.write("      margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li a {\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li a i {\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("      font-size: 1.1rem;\r\n");
      out.write("      color: #f6c90e;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar ul li a:hover,\r\n");
      out.write("    .sidebar ul li.active a {\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Main content */\r\n");
      out.write("    .main-content {\r\n");
      out.write("      flex-grow: 1;\r\n");
      out.write("      margin-left: 220px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      background-color: #f5f7fa;\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ===== ADMIN DASHBOARD SPECIFIC STYLES ===== */\r\n");
      out.write("\r\n");
      out.write("    .header {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      padding: 15px 20px;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      box-shadow: 0 2px 10px rgba(0,0,0,0.05);\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-info {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-info img {\r\n");
      out.write("      width: 40px;\r\n");
      out.write("      height: 40px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stats-container {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      box-shadow: 0 2px 10px rgba(0,0,0,0.05);\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-icon {\r\n");
      out.write("      width: 60px;\r\n");
      out.write("      height: 60px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      margin-right: 15px;\r\n");
      out.write("      font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-icon.flights { background-color: #e3f2fd; color: #1976d2; }\r\n");
      out.write("    .stat-icon.bookings { background-color: #e8f5e9; color: #388e3c; }\r\n");
      out.write("    .stat-icon.revenue  { background-color: #fff8e1; color: #ffa000; }\r\n");
      out.write("    .stat-icon.users    { background-color: #f3e5f5; color: #8e24aa; }\r\n");
      out.write("\r\n");
      out.write("    .stat-info h3 {\r\n");
      out.write("      font-size: 1.8rem;\r\n");
      out.write("      margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-info p {\r\n");
      out.write("      color: #666;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard-section {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      box-shadow: 0 2px 10px rgba(0,0,0,0.05);\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-header {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      padding-bottom: 10px;\r\n");
      out.write("      border-bottom: 1px solid #eee;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-header h3 {\r\n");
      out.write("      color: #0a1c2c;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-header a {\r\n");
      out.write("      color: #f6c90e;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table th, table td {\r\n");
      out.write("      padding: 12px 15px;\r\n");
      out.write("      text-align: left;\r\n");
      out.write("      border-bottom: 1px solid #eee;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table th {\r\n");
      out.write("      background-color: #f9f9f9;\r\n");
      out.write("      color: #555;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table tr:hover {\r\n");
      out.write("      background-color: #f5f7fa;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .status {\r\n");
      out.write("      padding: 5px 10px;\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      font-size: 0.8rem;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .status.confirmed { background-color: #e8f5e9; color: #388e3c; }\r\n");
      out.write("    .status.pending   { background-color: #fff8e1; color: #ffa000; }\r\n");
      out.write("    .status.cancelled { background-color: #ffebee; color: #d32f2f; }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("      padding: 8px 15px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("      transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-view {\r\n");
      out.write("      background-color: #e3f2fd;\r\n");
      out.write("      color: #1976d2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-view:hover {\r\n");
      out.write("      background-color: #bbdefb;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .charts-container {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: 2fr 1fr;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .chart-container {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      box-shadow: 0 2px 10px rgba(0,0,0,0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .chart-wrapper {\r\n");
      out.write("      height: 300px;\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("      position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 992px) {\r\n");
      out.write("      .charts-container {\r\n");
      out.write("        grid-template-columns: 1fr;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("      .sidebar {\r\n");
      out.write("        width: 70px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("      }\r\n");
      out.write("      .sidebar h2, .nav-menu li span {\r\n");
      out.write("        display: none;\r\n");
      out.write("      }\r\n");
      out.write("      .sidebar ul li {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 15px 0;\r\n");
      out.write("      }\r\n");
      out.write("      .sidebar ul li i {\r\n");
      out.write("        margin-right: 0;\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("      }\r\n");
      out.write("      .main-content {\r\n");
      out.write("        margin-left: 70px;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== PASSENGER-STYLE SIDEBAR (for Admin) ===== -->\r\n");
      out.write("  <div class=\"sidebar\">\r\n");
      out.write("    <h2>Dawn Airlines</h2>\r\n");
      out.write("    <ul class=\"nav-menu\">\r\n");
      out.write("      <li class=\"active\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminDashboard\">\r\n");
      out.write("          <i class=\"fas fa-tachometer-alt\"></i>\r\n");
      out.write("          <span>Dashboard</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/flightManagement\">\r\n");
      out.write("          <i class=\"fas fa-plane\"></i>\r\n");
      out.write("          <span>Flights</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookingManagement\">\r\n");
      out.write("          <i class=\"fas fa-ticket-alt\"></i>\r\n");
      out.write("          <span>Bookings</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/managePassengers\">\r\n");
      out.write("          <i class=\"fas fa-users\"></i>\r\n");
      out.write("          <span>Passengers</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manageStaff\">\r\n");
      out.write("          <i class=\"fas fa-user-tie\"></i>\r\n");
      out.write("          <span>Staff</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reportsAnalytics\">\r\n");
      out.write("          <i class=\"fas fa-chart-line\"></i>\r\n");
      out.write("          <span>Reports</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/settings\">\r\n");
      out.write("          <i class=\"fas fa-cog\"></i>\r\n");
      out.write("          <span>Settings</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== MAIN CONTENT AREA ===== -->\r\n");
      out.write("  <div class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("      <h2>Admin Dashboard</h2>\r\n");
      out.write("      <div class=\"user-info\">\r\n");
      out.write("        <img src=\"https://via.placeholder.com/40\" alt=\"Admin\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("          <p>Administrator</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Stats Cards -->\r\n");
      out.write("    <div class=\"stats-container\">\r\n");
      out.write("      <div class=\"stat-card\">\r\n");
      out.write("        <div class=\"stat-icon flights\">\r\n");
      out.write("          <i class=\"fas fa-plane\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-info\">\r\n");
      out.write("          <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.totalFlights}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("          <p>Total Flights</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"stat-card\">\r\n");
      out.write("        <div class=\"stat-icon bookings\">\r\n");
      out.write("          <i class=\"fas fa-ticket-alt\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-info\">\r\n");
      out.write("          <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.totalBookings}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("          <p>Total Bookings</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"stat-card\">\r\n");
      out.write("        <div class=\"stat-icon revenue\">\r\n");
      out.write("          <i class=\"fas fa-dollar-sign\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-info\">\r\n");
      out.write("          <h3>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.totalRevenue}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("          <p>Total Revenue</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"stat-card\">\r\n");
      out.write("        <div class=\"stat-icon users\">\r\n");
      out.write("          <i class=\"fas fa-users\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-info\">\r\n");
      out.write("          <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.totalUsers}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("          <p>Registered Users</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Recent Bookings Section -->\r\n");
      out.write("    <div class=\"dashboard-section\">\r\n");
      out.write("      <div class=\"section-header\">\r\n");
      out.write("        <h3>Recent Bookings</h3>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/bookings\">View All</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>Booking ID</th>\r\n");
      out.write("            <th>Passenger</th>\r\n");
      out.write("            <th>Flight</th>\r\n");
      out.write("            <th>Date</th>\r\n");
      out.write("            <th>Status</th>\r\n");
      out.write("            <th>Action</th>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("          <c:forEach items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.recentBookings}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" var=\"booking\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>#BK-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("              <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.passengerName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("              <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.flightCode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.route}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</td>\r\n");
      out.write("              <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.bookingDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <span class=\"status \r\n");
      out.write("                     ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.status == 'CONFIRMED' ? 'confirmed' \r\n                       : booking.status == 'PENDING' ? 'pending' \r\n                       : 'cancelled'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.status}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <button class=\"btn btn-view\" onclick=\"viewBooking(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booking.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">\r\n");
      out.write("                  View\r\n");
      out.write("                </button>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </c:forEach>\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Charts Section -->\r\n");
      out.write("    <div class=\"charts-container\">\r\n");
      out.write("      <div class=\"chart-container\">\r\n");
      out.write("        <div class=\"section-header\">\r\n");
      out.write("          <h3>Revenue Overview</h3>\r\n");
      out.write("          <select id=\"revenuePeriod\" onchange=\"updateRevenueChart()\">\r\n");
      out.write("            <option value=\"7\">Last 7 Days</option>\r\n");
      out.write("            <option value=\"30\" selected>Last 30 Days</option>\r\n");
      out.write("            <option value=\"90\">Last 90 Days</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chart-wrapper\">\r\n");
      out.write("          <canvas id=\"revenueChart\"></canvas>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"chart-container\">\r\n");
      out.write("        <div class=\"section-header\">\r\n");
      out.write("          <h3>Flight Status</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chart-wrapper\">\r\n");
      out.write("          <canvas id=\"flightStatusChart\"></canvas>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- ===== JAVASCRIPT CHART INITIALIZATION ===== -->\r\n");
      out.write("  <script>\r\n");
      out.write("    // Revenue Chart\r\n");
      out.write("    const revenueCtx = document.getElementById('revenueChart').getContext('2d');\r\n");
      out.write("    let revenueChart = new Chart(revenueCtx, {\r\n");
      out.write("      type: 'line',\r\n");
      out.write("      data: {\r\n");
      out.write("        labels: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.revenueLabels}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("        datasets: [{\r\n");
      out.write("          label: 'Daily Revenue ($)',\r\n");
      out.write("          data: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.revenueData}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("          backgroundColor: 'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("          borderColor: 'rgba(75, 192, 192, 1)',\r\n");
      out.write("          borderWidth: 2,\r\n");
      out.write("          tension: 0.3,\r\n");
      out.write("          fill: true\r\n");
      out.write("        }]\r\n");
      out.write("      },\r\n");
      out.write("      options: {\r\n");
      out.write("        responsive: true,\r\n");
      out.write("        maintainAspectRatio: false,\r\n");
      out.write("        scales: {\r\n");
      out.write("          y: {\r\n");
      out.write("            beginAtZero: true,\r\n");
      out.write("            grid: { color: 'rgba(0,0,0,0.05)' }\r\n");
      out.write("          },\r\n");
      out.write("          x: { grid: { display: false } }\r\n");
      out.write("        },\r\n");
      out.write("        plugins: {\r\n");
      out.write("          legend: { position: 'top' },\r\n");
      out.write("          tooltip: {\r\n");
      out.write("            callbacks: {\r\n");
      out.write("              label: function(context) {\r\n");
      out.write("                return '$' + context.raw.toLocaleString();\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Flight Status Chart\r\n");
      out.write("    const statusCtx = document.getElementById('flightStatusChart').getContext('2d');\r\n");
      out.write("    let statusChart = new Chart(statusCtx, {\r\n");
      out.write("      type: 'doughnut',\r\n");
      out.write("      data: {\r\n");
      out.write("        labels: ['On Time', 'Delayed', 'Cancelled', 'Completed'],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("          data: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.flightStatusData}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("          backgroundColor: [\r\n");
      out.write("            'rgba(54, 162, 235, 0.7)',\r\n");
      out.write("            'rgba(255, 206, 86, 0.7)',\r\n");
      out.write("            'rgba(255, 99, 132, 0.7)',\r\n");
      out.write("            'rgba(75, 192, 192, 0.7)'\r\n");
      out.write("          ],\r\n");
      out.write("          borderColor: [\r\n");
      out.write("            'rgba(54, 162, 235, 1)',\r\n");
      out.write("            'rgba(255, 206, 86, 1)',\r\n");
      out.write("            'rgba(255, 99, 132, 1)',\r\n");
      out.write("            'rgba(75, 192, 192, 1)'\r\n");
      out.write("          ],\r\n");
      out.write("          borderWidth: 1\r\n");
      out.write("        }]\r\n");
      out.write("      },\r\n");
      out.write("      options: {\r\n");
      out.write("        responsive: true,\r\n");
      out.write("        maintainAspectRatio: false,\r\n");
      out.write("        plugins: {\r\n");
      out.write("          legend: { position: 'right' },\r\n");
      out.write("          tooltip: {\r\n");
      out.write("            callbacks: {\r\n");
      out.write("              label: function(context) {\r\n");
      out.write("                const label = context.label || '';\r\n");
      out.write("                const value = context.raw || 0;\r\n");
      out.write("                const total = context.dataset.data.reduce((a, b) => a + b, 0);\r\n");
      out.write("                const percentage = Math.round((value / total) * 100);\r\n");
      out.write("                return `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${label}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${value}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${percentage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("%)`;\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Update revenue chart on period change\r\n");
      out.write("    function updateRevenueChart() {\r\n");
      out.write("      const period = document.getElementById('revenuePeriod').value;\r\n");
      out.write("      fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/revenueData?period=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${period}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`)\r\n");
      out.write("        .then(response => response.json())\r\n");
      out.write("        .then(data => {\r\n");
      out.write("          revenueChart.data.labels = data.labels;\r\n");
      out.write("          revenueChart.data.datasets[0].data = data.values;\r\n");
      out.write("          revenueChart.update();\r\n");
      out.write("        })\r\n");
      out.write("        .catch(err => console.error('Error fetching revenue data:', err));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // View booking details\r\n");
      out.write("    function viewBooking(bookingId) {\r\n");
      out.write("      window.location.href = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/bookings/view?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bookingId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
